letsencrypt:
  container_name: loomio-letsencrypt
  restart: always
  image: jrcs/letsencrypt-nginx-proxy-companion
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./certificates:/etc/nginx/certs:rw
  volumes_from:
    - nginx

nginx:
  container_name: loomio-nginx
  restart: always
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./certificates:/etc/nginx/certs:ro
    - ./nginx/vhost.d:/etc/nginx/vhost.d
    - ./nginx/conf.d/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    - ./nginx/html:/usr/share/nginx/html
  ports:
    - 80:80
    - 443:443
  links:
    - app

app:
  container_name: loomio-app
  restart: always
  image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  expose:
    - 3000
  env_file: ./env
  links:
    - db
    - redis
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
    - REDIS_URL=redis://redis:6379
  volumes:
    - ./client:/loomio/public/client
    - ./uploads:/loomio/public/system
    - ./files:/loomio/public/files
    - ./plugins:/loomio/plugins/docker
    - ./import:/import

worker:
  container_name: loomio-worker
  restart: always
  image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  env_file: ./env
  links:
    - db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
    - TASK=worker
  volumes:
    - ./client:/loomio/public/client
    - ./uploads:/loomio/public/system
    - ./files:/loomio/public/files
    - ./plugins:/loomio/plugins/docker

db:
  container_name: loomio-db
  restart: always
  image: postgres:${POSTGRES_CONTAINER_TAG}
  volumes:
    - ./pgdata:/pgdata
    - ./pgdumps:/pgdumps
  environment:
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=loomio_production
   - PGDATA=/pgdata

redis:
  container_name: loomio-redis
  restart: always
  image: redis:5.0

mailin:
  container_name: loomio-mailin
  restart: always
  image: ${MAILIN_CONTAINER_IMAGE}:${MAILIN_CONTAINER_TAG}
  ports:
    - "25:25"
  links:
    - app
  environment:
    - WEBHOOK_URL=http://app:3000/email_processor/
