letsencrypt:
  restart: always
  image: jrcs/letsencrypt-nginx-proxy-companion
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./certificates:/etc/nginx/certs:rw
  volumes_from:
    - nginx

nginx:
  restart: always
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./certificates:/etc/nginx/certs:ro
    - ./nginx/vhost.d:/etc/nginx/vhost.d
    - ./nginx/conf.d/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    - ./nginx/html:/usr/share/nginx/html
  ports:
    - 80:80
    - 443:443
  links:
    - loomio

loomio:
  restart: always
  image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  expose:
    - 3000
  env_file: ./env
  links:
    - db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
  volumes:
    - ./uploads:/loomio/public/system
    - ./files:/loomio/public/files
    - ./plugins:/loomio/plugins/docker
    - ./client:/loomio/public/client

worker:
  restart: always
  image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  env_file: ./env
  links:
    - db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
    - TASK=worker
  volumes:
    - ./uploads:/loomio/public/system
    - ./files:/loomio/public/files
    - ./plugins:/loomio/plugins/docker
    - ./client:/loomio/public/client

db:
  restart: always
  image: postgres:9.6
  volumes:
    - ./pgdata:/pgdata
  environment:
   - POSTGRES_PASSWORD=password
   - PGDATA=/pgdata

mailin:
  restart: always
  image: ${MAILIN_CONTAINER_IMAGE}:${MAILIN_CONTAINER_TAG}
  ports:
    - "25:25"
  links:
    - loomio
  environment:
    - WEBHOOK_URL=http://loomio:3000/email_processor/
